name: Modyo Widget Publish

# Trigger Events
on:
  workflow_dispatch:
  
  push:
    branches:
      - demo
      
# Jobs to run
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    env:
      CI: true
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
        
      # Install NodeJS
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      # Install and build Widget
      - name: Install dependencies
        run: |
          npm install
          npm i -g @modyo/cli
          npm run build
          
      # Update .env File
      - name: 'Create env file'
        run: |
          touch .env
          echo MODYO_TOKEN=${{ secrets.API_KEY }} >> .env
          cat .env

      # Push Widget to Modyo
      - name: push
        run: | 
          modyo-cli push dev-demo-modyo-ci
